[package]
name = "split"
version = "2.0.0-alpha.1"
description = "Lightweight Deadlock savestate utility"
authors = ["necrozzzzzz"]
edition = "2021"
rust-version = "1.95"
default-run = "split"

[lib]
name = "split_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
notify = "8.2.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
sysinfo = "0.39.6"
tauri = { version = "2.11.5", features = ["tray-icon"] }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-single-instance = "2"
thiserror = "2"

windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
